// import { useCinemaStore } from "~/stores/user/useCinemaStore";
import { useMovieStore } from "@/stores/user/useMovieStore.js";
import { useCinemaStore } from '~/stores/user/useCinemaStore'
export const useBooking = () => {

const seats = ref([
    {seatLine:'A',seatNumber:'1',seatStatus:2,seatType:1},
    {seatLine:'A',seatNumber:'2',seatStatus:2,seatType:1},
    {seatLine:'A',seatNumber:'3',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'4',seatStatus:2,seatType:1},
    {seatLine:'A',seatNumber:'5',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'6',seatStatus:2,seatType:1},
    {seatLine:'A',seatNumber:'7',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'8',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'9',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'10',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'11',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'12',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'13',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'14',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'15',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'16',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'17',seatStatus:1,seatType:1},
    {seatLine:'A',seatNumber:'18',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'1',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'2',seatStatus:2,seatType:1},
    {seatLine:'B',seatNumber:'3',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'4',seatStatus:2,seatType:1},
    {seatLine:'B',seatNumber:'5',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'6',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'7',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'8',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'9',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'10',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'11',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'12',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'13',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'14',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'15',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'16',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'17',seatStatus:1,seatType:1},
    {seatLine:'B',seatNumber:'18',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'1',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'2',seatStatus:2,seatType:1},
    {seatLine:'C',seatNumber:'3',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'4',seatStatus:2,seatType:1},
    {seatLine:'C',seatNumber:'5',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'6',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'7',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'8',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'9',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'10',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'11',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'12',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'13',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'14',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'15',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'16',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'17',seatStatus:1,seatType:1},
    {seatLine:'C',seatNumber:'18',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'1',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'2',seatStatus:2,seatType:1},
    {seatLine:'D',seatNumber:'3',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'4',seatStatus:3,seatType:1},
    {seatLine:'D',seatNumber:'5',seatStatus:4,seatType:1},
    {seatLine:'D',seatNumber:'6',seatStatus:2,seatType:1},
    {seatLine:'D',seatNumber:'7',seatStatus:4,seatType:1},
    {seatLine:'D',seatNumber:'8',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'9',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'10',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'11',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'12',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'13',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'14',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'15',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'16',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'17',seatStatus:1,seatType:1},
    {seatLine:'D',seatNumber:'18',seatStatus:1,seatType:1},
    {seatLine:'E',seatNumber:'1',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'2',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'3',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'4',seatStatus:2,seatType:2},
    {seatLine:'E',seatNumber:'5',seatStatus:4,seatType:2},
    {seatLine:'E',seatNumber:'6',seatStatus:2,seatType:2},
    {seatLine:'E',seatNumber:'7',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'8',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'9',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'10',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'11',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'12',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'13',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'14',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'15',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'16',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'17',seatStatus:1,seatType:2},
    {seatLine:'E',seatNumber:'18',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'1',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'2',seatStatus:2,seatType:2},
    {seatLine:'F',seatNumber:'3',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'4',seatStatus:2,seatType:2},
    {seatLine:'F',seatNumber:'5',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'6',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'7',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'8',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'9',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'10',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'11',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'12',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'13',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'14',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'15',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'16',seatStatus:1,seatType:2},
    {seatLine:'F',seatNumber:'17',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'1',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'2',seatStatus:2,seatType:2},
    {seatLine:'G',seatNumber:'3',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'4',seatStatus:2,seatType:2},
    {seatLine:'G',seatNumber:'5',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'6',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'7',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'8',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'9',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'10',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'11',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'12',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'13',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'14',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'15',seatStatus:1,seatType:2},
    {seatLine:'G',seatNumber:'16',seatStatus:1,seatType:2},
    {seatLine:'h',seatNumber:'1',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'2',seatStatus:2,seatType:2},
    {seatLine:'H',seatNumber:'3',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'4',seatStatus:2,seatType:2},
    {seatLine:'H',seatNumber:'5',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'6',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'7',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'8',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'9',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'10',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'11',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'12',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'13',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'14',seatStatus:1,seatType:2},
    {seatLine:'H',seatNumber:'15',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'1',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'2',seatStatus:2,seatType:2},
    {seatLine:'I',seatNumber:'3',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'4',seatStatus:2,seatType:2},
    {seatLine:'I',seatNumber:'5',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'6',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'7',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'8',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'9',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'10',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'11',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'12',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'13',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'14',seatStatus:1,seatType:2},
    {seatLine:'I',seatNumber:'15',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'1',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'2',seatStatus:2,seatType:2},
    {seatLine:'K',seatNumber:'3',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'4',seatStatus:2,seatType:2},
    {seatLine:'K',seatNumber:'5',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'6',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'7',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'8',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'9',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'10',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'11',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'12',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'13',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'14',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'15',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'16',seatStatus:1,seatType:2},
    {seatLine:'K',seatNumber:'17',seatStatus:1,seatType:2},
])

const nameOfCinema =  computed(() => {
    return useCinemaStore().nameOfCinema
})

const movieDetail = computed(() => {
    return useMovieStore().movieDetail
})

const totalMoney = ref('')

const seatSelected = ref([])

const note_seat_status = ref([
    {linkImage:'/img/seat-unselect-normal-intro.png',text:'Ghế trống'},
    {linkImage:'/img/seat-select-normal-intro.png',text:'Ghế đang chọn'},
    {linkImage:'/img/seat-process-normal-intro.png',text:'Ghế đang được giữ'},
    {linkImage:'/img/seat-buy-normal-intro.png',text:'Ghế đã bán'}
])

  
  return {
    nameOfCinema,
    movieDetail,
    totalMoney,
    seatSelected,
    note_seat_status,
    seats
  }

}
